version: '3.8'

services:

  # Web Server Service
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - app
      - db
    networks:
      - laravel

  #Database Service
  db:
    image : mysql
    container_name : mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - "33069:33069"
    environment:
      MYSQL_DATABASE: edulogros
      MYSQL_ROOT_PASSWORD: password
    networks:
      - laravel
  # db:
  #  image: postgres
  #  container_name: postgres
  #  volumes:
  #    - ./postgresql/data:/var/lib/postgresql/data
  #  ports:
  #    - "5432:5432"
  #  environment: 
  #    POSTGRES_DB: blog
  #    POSTGRES_USER: root 
  #    POSTGRES_PASSWORD: password 

  # Application Service
  app:
    container_name: edulogros
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www
    ports:
      - "9000:9000"
    working_dir: /var/www
    networks:
      - laravel

  #phpMyAdmin Service
  phpmyadmin:
     image: phpmyadmin/phpmyadmin
     container_name: phpmyadmin
     ports:
       - "3400:80"
     depends_on:
       - db
     networks:
       - laravel

  # pgadmin:
  # image: dpage/pgadmin4
  # container_name: pgAdmin
  # ports:
  #   - "5050:80"
  # depends_on:
  #   - db 
  # environment:
  #   PGADMIN_DEFAULT_EMAIL: reinaldodu@gmail.com
  #   PGADMIN_DEFAULT_PASSWORD: password
networks:
  laravel:
